<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__vfb-7</name>
   <tag></tag>
   <elementGuidId>6dcb9b49-f4c1-4f9d-a07f-399b093e3389</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vfb-7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f43a1ff-fc81-467c-b99d-d0d04a9b0c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>90113ce4-f026-4012-995f-8f06f052379c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-7</value>
      <webElementGuid>7a7da872-00c7-4d99-9fe1-9d1c2c308659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-7</value>
      <webElementGuid>861cd754-5a2e-42e2-b4b1-edae0c89d57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text  vfb-medium  required  </value>
      <webElementGuid>390da21e-0962-41a0-a9cc-9c85a97a5b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-7&quot;)</value>
      <webElementGuid>20f4ce15-d5de-494e-b42c-657d364fdad5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-7']</value>
      <webElementGuid>02057908-a0d1-43c8-a8c1-7bd9d53286c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-7']/input</value>
      <webElementGuid>19feb528-ceb3-49a0-a3df-2f9698b0bf5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>a4dfb92f-d36c-4317-98bb-2253b5e910fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vfb-7' and @id = 'vfb-7']</value>
      <webElementGuid>3cdafe31-3897-47cc-8e20-5a3dd59553a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
