<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Afghanistan</name>
   <tag></tag>
   <elementGuidId>c5da9ae2-a9c9-4b78-8d66-589cc5595850</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-vfb-13-country-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-vfb-13-country-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4c5feaa3-a5e0-4bb6-b535-df7da8013458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>39a0ae53-c29b-4445-8257-e3d4b39497b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-vfb-13-country-container</value>
      <webElementGuid>9d475286-ad5d-4b19-b886-55d89903e0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>959e506a-9769-4789-b1b4-e766b2662765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f792dd19-b323-4cf1-bfbb-de5db0fa1432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Afghanistan</value>
      <webElementGuid>10d57d27-95e5-46e0-a513-5ecb23b9c6ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Afghanistan</value>
      <webElementGuid>c54e4572-51d3-4884-9732-e27b79cfcf38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-vfb-13-country-container&quot;)</value>
      <webElementGuid>0b8e9634-9d61-4f61-b203-b86f79c4c8e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-vfb-13-country-container']</value>
      <webElementGuid>bf3d5678-3520-4486-a4d2-00cc8b178649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-13']/div/span[6]/span/span/span/span</value>
      <webElementGuid>8e5da48a-79a6-4500-b794-5be958e8486a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postal / Zip Code'])[1]/following::span[5]</value>
      <webElementGuid>0ba92e29-b754-4a3f-ad8e-807e53e7835b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State / Province / Region'])[1]/following::span[6]</value>
      <webElementGuid>7ebad80e-3b15-4277-8055-f6dfe7e02b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/preceding::span[3]</value>
      <webElementGuid>5574e1ca-265b-40b7-acd0-b044fe52d094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[6]/span/span/span/span</value>
      <webElementGuid>43e960b7-4db7-4ce8-9356-9bfc1a1e0e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-vfb-13-country-container' and @title = 'Afghanistan' and (text() = 'Afghanistan' or . = 'Afghanistan')]</value>
      <webElementGuid>ead6e271-4060-4e95-9700-ba4ee60dd33c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
