<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__vfb-3</name>
   <tag></tag>
   <elementGuidId>87dcd68b-9148-4282-8281-fc6cb67cfc4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vfb-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d06f93d-2386-4570-a4ad-32057760e72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4c53d9ca-29f9-48cd-8e70-bf7a4673131c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-3</value>
      <webElementGuid>b8bd52c8-aa63-42c6-8a05-e86c3396432f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-3</value>
      <webElementGuid>3df17a81-6a08-41c2-81b0-dcd2eef449be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text  vfb-medium  required {digits:true,maxlength:2,minlength:2} </value>
      <webElementGuid>e830226c-31d4-4c04-98a1-409af56a5c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-3&quot;)</value>
      <webElementGuid>10578b9f-d169-4af0-aa62-f6d439bf9073</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-3']</value>
      <webElementGuid>3859f8c4-da04-4a67-884f-0b08bf228e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='item-vfb-2']/ul/li/span/input</value>
      <webElementGuid>2986b61f-d119-4709-8dd5-b7f63557ec37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/ul/li/span/input</value>
      <webElementGuid>b3ca1e7f-e5ba-451a-bec9-0133c8a79e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vfb-3' and @id = 'vfb-3']</value>
      <webElementGuid>a37fff90-cf03-47dd-a3b7-60afa39c4c11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
