<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gender_vfb-31</name>
   <tag></tag>
   <elementGuidId>ae446942-9a2f-4633-a30b-7421f0827519</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-31-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vfb-31-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fddab1b7-a8ee-4b8e-8827-7841ea5a5ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e63f9d05-fe4f-47df-95b4-13bf96bc7f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-31</value>
      <webElementGuid>8c816763-1b7c-45fb-8934-9d7107d07556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-31-1</value>
      <webElementGuid>8671a908-8976-4b9a-a0e5-9f367b3f34cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>67bf080f-e15e-4893-9d40-723dfd1c27c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-radio   name</value>
      <webElementGuid>aa79d5ac-4d45-473b-bbdd-9b9b0b4d5a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-31-1&quot;)</value>
      <webElementGuid>7eafee48-e888-4a0b-9381-e85745b5d56c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-31-1']</value>
      <webElementGuid>17723ebd-d976-4dba-b781-9e8feed5c462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-31']/div/span/input</value>
      <webElementGuid>ade2b47b-c269-4f43-b896-be27e9287c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>0e303630-3b39-4cd9-8edf-93cfdd68bf2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'vfb-31' and @id = 'vfb-31-1']</value>
      <webElementGuid>8c8ba44b-cf7d-42ee-a427-f205069107e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
