<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Demo_vfb-18</name>
   <tag></tag>
   <elementGuidId>391d237b-7f41-4b06-a62c-025c17b3b18b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-18']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vfb-18</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2440caed-b46a-48ec-a4f2-7edf28bade25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e8be8dfe-a2dd-4613-b0ef-b475aa8e210e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-18</value>
      <webElementGuid>1a341be8-5275-447a-8214-a2a45a0ad44d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-18</value>
      <webElementGuid>3cda64c6-c004-4f15-8f41-22d7212ca11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text vfb-date-picker vfb-medium hasDatepicker</value>
      <webElementGuid>327fd9d5-83c3-4ed3-a4ca-55b0e3e5c4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dp-dateformat</name>
      <type>Main</type>
      <value>mm/dd/yy</value>
      <webElementGuid>c52b2921-6e4b-41b1-83bf-7ddb876a1792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-18&quot;)</value>
      <webElementGuid>b08cd4c5-31ab-411f-9d02-aba17395b3df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-18']</value>
      <webElementGuid>84f642fc-e96b-48f8-8fe4-4943a4f96cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-18']/span/input</value>
      <webElementGuid>4789bd56-037b-4a33-b680-da8ea59affdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/span/input</value>
      <webElementGuid>af71dcd0-a0df-403a-b98a-cff3f7a0e9d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vfb-18' and @id = 'vfb-18']</value>
      <webElementGuid>57a4935a-6966-4dd9-9648-c98c169db0c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
